version: "3.9"

services:
  db:
    image: postgres:latest
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: edu_learn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mahi123@#
      PORT: 5432

  web:
    build: .
    # command: gunicorn --bind 0.0.0.0:8000 project.wsgi:application
    command: python3 manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg-dev-data:
