# Generated by Django 5.0.1 on 2024-04-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_course_image_alter_course_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
