"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url



load_dotenv()

# from project import project

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-nyl81lm%_ri86=j84wo1%gzqi1i+5&0k$wqxymbkb6m5ob_czv'
SECRET_KEY = os.environ.get("SECRET_KEY")



# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.environ.get("DEBUG", "False").lower() == 'true'


# ALLOWED_HOSTS = ['localhost', '127.0.0.1']
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")


CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:8000',
    'http://127.0.0.1:3000',
    'http://0.0.0.0:8000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',

]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CSRF_COOKIE_SECURE = True
# CSRF_COOKIE_SAMESITE = 'None'  # or 'Strict' depending on your requirements



REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
    #   'rest_framework.permissions..IsAuthenticatedOrReadOnly',],
        'rest_framework.permissions.IsAuthenticated',],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.SessionAuthentication',  # If you still want to use SessionAuthentication
        'rest_framework.authentication.TokenAuthentication',
    ],
}

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',),
}


CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS=True

ROOT_URLCONF = 'project.urls'

APPEND_SLASH = False


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

database_url=os.environ.get("DATABASE_URL")

DOCKER_ENV = os.getenv('DOCKER_ENV', 'false').lower() == 'true'

DATABASES = {
    'default': dj_database_url.parse(database_url)
}
# DATABASES = {
#     'default': dj_database_url.parse("postgres://edulearn_db_user:llLdgaEb2tGGDrc2aEzMCqUpfAankM84@dpg-cok9srgl5elc73c1drug-a.oregon-postgres.render.com/edulearn_db")
# }

# if DOCKER_ENV:
#     # Use Docker database host
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': 'edu_learn',
#             'USER': 'postgres',
#             'PASSWORD': 'mahi123@#',
#             'HOST': 'db',  # Docker database host
#             'PORT': '5432',
#         }
#     }
# else:
#     # Use localhost database configuration
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': 'edu_learn',
#             'USER': 'postgres',
#             'PASSWORD': 'mahi123@#',
#             'HOST': 'localhost',  # Local database host
#             'PORT': '5432',
#         }
#     }

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     # 'default': {
#     #     'ENGINE': 'django.db.backends.sqlite3',
#     #     'NAME': BASE_DIR / 'db.sqlite3',
#     # }
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'edu_learn',
#         'USER': 'postgres',
#         'PASSWORD': 'mahi123@#',
#         'HOST': 'db',
#         'PORT': '5432',       
        
#     },
#     'test': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('PG_TEST_DATABASE'),
#         'USER': os.getenv('PG_USER'),
#         'PASSWORD': os.getenv('PG_PASSWORD'),
#         'HOST': 'db',
#         'PORT': '5432',
#     },
    
# }



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

# project/settings.py
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default authentication backend
    # 'app.backends.CustomUserBackend',  # Path to your custom authentication backend
]

# AUTH_USER_MODEL = 'app.CustomUser'

AUTH_USER_MODEL = 'app.AppUser'


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
